language: python
python:
  - "2.7"
# - "3.5"   To Do - Add support to it !
# - "pypy"  To Do - Check about it later
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - pip install pep8
  - pip install pylint
# command to run tests
script:
  - nosetests
after_script:
  - pep8 .
  - pylint JenkinsStatistics
